# This is a basic workflow to help you get started with Actions

name: Scheduled API Call

on:
  schedule:
    - cron: '*/8 * * * *'  # 每15分钟执行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl -X GET \
               -H "Content-Type: application/json" \
               https://line-household-account-book-py.onrender.com
